include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy

variables:
  TF_VERSION: "1.3.7"
  TF_IMAGE: "gitlab-org/terraform-images/releases/terraform:${TF_VERSION}"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

validate_terraform:
  stage: validate
  image: ${TF_IMAGE}
  script:
    - terraform init
    - terraform validate

plan_terraform:
  stage: build
  image: ${TF_IMAGE}
  script:
    - terraform init
    - terraform plan -out=aws_test.plan
  needs:
    - "validate_terraform"
  artifacts:
    paths:
      - build.plan

Apply terraform:
  stage: deploy
  image: ${TF_IMAGE}
  script:
    - terraform init
    - terraform apply -input=false -auto-approve build.plan
  needs:
    - "plan_terraform"
  dependencies:
    - "plan_terraform"
