include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

validate_terraform:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan_terraform:
  stage: build
  script:
    - terraform init
    - terraform plan -out=build.plan
  needs:
    - "validate_terraform"
  artifacts:
    paths:
      - build.plan

Apply terraform:
  stage: deploy
  script:
    - terraform init
    - terraform apply -input=false -auto-approve build.plan
  needs:
    - "plan_terraform"
  dependencies:
    - "plan_terraform"
